### ISSUE TITLE
09/12 MVPレビュー依頼提出

### ISSUE THREAD

**Issue by aio97** [aio97/runteq_graduation_app#26]
## 各種情報
[私のしおり](https://watashi-no-shiori.onrender.com/)
旅行のしおり作成・共有サービスです。

## READMEレビュー時にMVPリリース時点で実装予定だった機能
  - 会員登録
  - ログイン
  - しおり作成
  - しおり一覧
  - しおり編集、削除

レビューのほどよろしくお願いいたします。

**Comment by tarakish** [comment]
開発お疲れ様です！
確認しました。以下コメントです！

---

- 会員登録後、トップページに遷移しますがその場合は会員登録と同時にログインさせるとユーザーの手間が減ってよいかと思いました。
  - もしくはトップページではなくログインページに遷移させるなどでもよいかと思います。

- 会員登録時の入力必須項目について
  - 性別、年代は入力必須項目ではないかと思いますが、その場合は入力が必須な項目とそうでない項目がUI上でわかりやすいようにできると良いと思います。
  - 特に性別などは入力したくないユーザーも一定数いるかと思いますが、サービス上でこの情報はどこかに使われていますか？

- しおりの新規作成時、および編集時にプランの追加ができませんでした。リロードした場合は問題なく出来たこととコンソール上でエラーが出ているのでおそらくJSの読み込み周りでうまく行っていない箇所がありそうなのでこちらの修正をお願いします。
[![Image from Gyazo](https://i.gyazo.com/7186aa19d452448265227a8ffc924db2.gif)](https://gyazo.com/7186aa19d452448265227a8ffc924db2)

**Comment by aio97** [comment]
レビューありがとうございます。
コメントいただいた点について修正いたしました。
  
 - 会員登録後の遷移をトップページからログインページへ変更しました。
 - 会員登録時の入力必須項目についてページに記述追加しました。（性別、年代は任意としていましたが、明示していなかったため修正しました。）
 - しおり新規作成時、編集時のプラン追加ボタンの挙動について修正しました。
  
再度、レビューのほどよろしくお願いいたします。

**Comment by tarakish** [comment]
修正確認しました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下も取り組む =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
