### ISSUE TITLE
”Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by aio97** [aio97/runteq_graduation_app#4]
■Webアプリの概要
旅行のしおりを作成できるサービスです。
ユーザーの思うままにカスタマイズしてしおりを作成できます。
作成したしおりを共有することで旅行先の情報収集ができます。

■ProjectsのURL
(https://github.com/users/aio97/projects/1/views/1?sumFields=%5B129202309%5D&hideItemsCount=false)

■MVPリリースまで
- [ ] rails new
- [ ] Renderにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] しおり作成機能

■MVP後
- [ ] 作成しおり一覧
- [ ] ブックマーク
- [ ] 登録情報変更
- [ ] パスワードリセット機能
- [ ] GoogleMap
- [ ] マルチ検索機能
- [ ] パスワード更新
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] RSpec（モデルテスト・システムテスト）

■MVPレビュー依頼予定日
予定日：2024年 9月 12日

**Comment by kashiwagi-rena** [comment]
<img width="888" alt="スクリーンショット 2024-08-31 14 50 42" src="https://github.com/user-attachments/assets/e7ffef25-99b3-49d6-bb0a-17992a9ef9f1">

対応ありがとうございます。
Projectsページにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでし
た。
カリキュラムをご確認いただいて、レビューワー側で上記が確認できるように対応いただき、再提出操作をお願いいたします。

**Comment by aio97** [comment]
コメントありがとうございます。

projectをpublic設定に直し、再度提出しました。
レビューよろしくお願いいたします。

[プロジェクトURL]
https://github.com/users/aio97/projects/1/views/1

**Comment by kashiwagi-rena** [comment]
確認取れました！
以下コメントです。

---

- 「パスワード更新」のTodoが存在しないようです。
- ストーリーポイント５以上のものがあるようです。現状で実装が思い浮かばない場合は、実装方法を調べるタスクと実装タスク二つに分けて、調べるときは調べることに集中できるようにissueを分けていただくと進捗を感じながら実装することが可能だと認識しております。また、調べている際にわからないものが出てきた際に技術面談を使用していただき確認することも可能と認識しております。以上の観点からストーリーポイントをもう少し分けていただきたいです。ご検討よろしくお願いします。

**Comment by aio97** [comment]
レビュー、コメントありがとうございます。
ご指摘いただいた点を修正しました。
再度、ご確認のほどよろしくお願いいたします。
  
  
 -  「パスワード更新」について、登録情報変更機能で実装しようと考えております。
[![Image from Gyazo](https://i.gyazo.com/47e672686845af688ff58a41ac16abca.png)](https://gyazo.com/47e672686845af688ff58a41ac16abca)
 - ストーリーポイントが5以上のものを分割しました。

**Comment by tarakish** [comment]
修正確認しました。LGTMです！
MVPリリースに向けて開発頑張ってください！
